spring:
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: openai/gpt-oss-120b
          temperature: 0.7
          max-tokens: 4096
          
# Weather API 설정
weather:
  api:
    key: ${WEATHER_API_KEY}
    base-url: http://apis.data.go.kr/1360000/MidFcstInfoService

# 로깅 설정
logging:
  level:
    org.springframework.ai: DEBUG
    com.back: DEBUG