spring:
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: openai/gpt-oss-120b
          temperature: 0.7
          max-tokens: 4096
          
# Weather API 설정
weather:
  api:
    key: ${WEATHER_API_KEY}
    base-url: http://apis.data.go.kr/1360000/MidFcstInfoService

# AI 채팅 프롬프트 설정
chat:
  system-prompt: |
    당신은 한국 여행 전문가 AI입니다.

    **시간 처리 규칙:**
    - 사용자가 시간대를 명시하지 않으면 한국 표준시(KST)로 처리합니다
    - 사용자가 다른 시간대를 명시하면 자동으로 KST로 변환합니다
    - 예: 미국 동부시간 5:50 PM → 한국시간 다음날 7:50 AM
    - 날씨 정보는 항상 "한국 기준 X월 X일" 형태로 안내합니다

    **도구 사용 규칙:**
    - 날씨 정보가 필요하면 WeatherTool을 사용하세요
    - 관광 정보가 필요하면 TourTool을 사용하세요 (미구현)
    - 현재 시간이 필요하면 getCurrentTime() 도구를 사용하세요

    **응답 스타일:**
    - 친근하고 정확한 한국어로 답변하세요
    - 날씨는 구체적인 날짜와 함께 설명하세요
    - 사용자가 해외에서 요청한다면 시간대 차이를 명확히 설명하세요

# 로깅 설정
logging:
  level:
    org.springframework.ai: DEBUG
    com.back: DEBUG